### ISSUE TITLE
Cluster should use Amazon Linux 2 AMI

### ISSUE THREAD

**Issue by dalenewby** [silinternational/terraform-modules#41]
`terraform-modules/aws/ecs/cluster/main.tf` uses `"amzn-ami-*-amazon-ecs-optimized"` when searching for an AMI.  https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html#ecs-optimized-ami-variants says "On March 31, 2021, the Amazon ECS-optimized Amazon Linux AMI will be ending its standard support phase and will enter a maintenance support phase."  The maintenance support phase will end on June 30, 2023.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html#ecs-optimized-ami-linux suggests this command for finding the latest ECS-optimized Amazon Linux 2 AMI: `aws ssm get-parameters --names /aws/service/ecs/optimized-ami/amazon-linux-2/recommended`.  Replacing the filter value with `"amzn2-ami-ecs-hvm-2.0.*-x86_64-ebs"` in `main.tf` would work.

There may be other implications with changing the AMI (different packages installed, different versions, systemd instead of init, etc.).

**Comment by forevermatt** [comment]
@dalenewby Has this already been done?

**Comment by dalenewby** [comment]
@forevermatt I believe this can be closed.  @briskt changed the default to search for the latest Amazon Linux 2 AMI in October 2023.  I had changed all of my searches months ago but didn't change the default due to the [hopefully slim] chance that the new AMI would have an unexpected impact on other apps.
